# This formula is auto-generated by the `update-homebrew` job in the
# main repo's release workflow on every published version tag.
#
# The `0.0.0` placeholder + zeroed sha256 mean the tap is dormant
# until the first real release lands. After that, the action
# overwrites this file with the real version + hashes.
class Drip < Formula
  desc "Delta Read Interception Proxy — sends only file diffs to your LLM agent"
  homepage "https://github.com/drip-cli/drip"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/drip-cli/drip/releases/download/v0.0.0/drip-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/drip-cli/drip/releases/download/v0.0.0/drip-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drip-cli/drip/releases/download/v0.0.0/drip-aarch64-unknown-linux-musl.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/drip-cli/drip/releases/download/v0.0.0/drip-x86_64-unknown-linux-musl.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "drip"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/drip --version")
  end
end
